const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const contractSchema = new Schema(
    {
        depositId: { type: mongoose.Schema.Types.ObjectId, ref: 'deposit', required: true, unique: true },
        roomId: { type: mongoose.Schema.Types.ObjectId, ref: 'posts', required: true, index: true },
        tenantId: { type: mongoose.Schema.Types.ObjectId, ref: 'user', required: true, index: true },
        landlordId: { type: mongoose.Schema.Types.ObjectId, ref: 'user', required: true, index: true },
        contractCode: { type: String, required: true, unique: true, index: true },
        monthlyRent: { type: Number, required: true, min: 0 },
        depositAmount: { type: Number, required: true, min: 0 },
        startDate: { type: Date, required: true },
        endDate: { type: Date, required: true },
        paymentFromDay: { type: Number, min: 1, max: 31, default: 1 },
        paymentToDay: { type: Number, min: 1, max: 31, default: 5 },
        electricityRate: { type: Number, min: 0, default: 0 },
        waterRate: { type: Number, min: 0, default: 0 },
        otherMonthlyFee: { type: Number, min: 0, default: 0 },
        otherFeeNote: { type: String, trim: true, maxlength: 500, default: '' },
        landlordIdentityNumber: { type: String, trim: true, maxlength: 30, default: '' },
        landlordIdentityIssueDate: { type: Date, default: null },
        landlordIdentityIssuePlace: { type: String, trim: true, maxlength: 200, default: '' },
        tenantIdentityNumber: { type: String, trim: true, maxlength: 30, default: '' },
        tenantIdentityIssueDate: { type: Date, default: null },
        tenantIdentityIssuePlace: { type: String, trim: true, maxlength: 200, default: '' },
        landlordBankAccount: { type: String, trim: true, maxlength: 50, default: '' },
        landlordBankName: { type: String, trim: true, maxlength: 120, default: '' },
        terms: { type: String, required: true, trim: true },
        legalAcknowledgement: {
            type: String,
            trim: true,
            default:
                'Hợp đồng này được giao kết hoàn toàn bằng phương thức điện tử dựa trên tinh thần tự nguyện của hai bên, phù hợp với Luật Giao dịch điện tử và Bộ luật Dân sự Việt Nam (p. 2).\n Hai bên cam kết số điện thoại và email khai báo trên hệ thống thuộc quyền sở hữu, quản lý duy nhất của chính mình. Việc nhập đúng mã OTP gửi về số điện thoại thể hiện ý chí trực tiếp và không thể phủ nhận của các bên (p. 2). Lịch sử hệ thống (Log file) ghi nhận thời gian, mã OTP, địa chỉ IP và thiết bị ký là chứng cứ pháp lý duy nhất, có giá trị chứng cứ tuyệt đối trước pháp luật mà không cần ký tay vào bản giấy (p. 2).',
                
        },
        tenantSignatureUrl: { type: String, default: '' },
        landlordSignatureUrl: { type: String, default: '' },
        tenantSignedAt: { type: Date, default: null },
        landlordSignedAt: { type: Date, default: null },
        tenantSignatureOtpHash: { type: String, default: '' },
        tenantSignatureOtpExpires: { type: Date, default: null },
        tenantSignatureOtpVerifiedAt: { type: Date, default: null },
        tenantSignatureVerifiedPhone: { type: String, trim: true, default: '' },
        tenantSignatureIp: { type: String, trim: true, default: '' },
        tenantSignatureUserAgent: { type: String, trim: true, default: '' },
        landlordSignatureOtpHash: { type: String, default: '' },
        landlordSignatureOtpExpires: { type: Date, default: null },
        landlordSignatureOtpVerifiedAt: { type: Date, default: null },
        landlordSignatureVerifiedPhone: { type: String, trim: true, default: '' },
        landlordSignatureIp: { type: String, trim: true, default: '' },
        landlordSignatureUserAgent: { type: String, trim: true, default: '' },
        pdfUrl: { type: String, default: '' },
        pdfPublicId: { type: String, default: '' },
        status: {
            type: String,
            enum: [
                'draft',
                'waiting_tenant_signature',
                'waiting_landlord_signature',
                'active',
                'expired',
                'canceled',
            ],
            default: 'draft',
            index: true,
        },
        sentToTenantAt: { type: Date, default: null },
        sentToLandlordAt: { type: Date, default: null },
        canceledAt: { type: Date, default: null },
        cancelReason: { type: String, trim: true, default: '' },
    },
    { timestamps: true },
);

module.exports = mongoose.model('contract', contractSchema);
